#!/usr/bin/env node
// Regenerates idea map pages + pages.json from GitHub issues.
// Runs in GitHub Actions on issue events. No dependencies.
const { execSync } = require("child_process");
const fs = require("fs");

const REPO = "TR3-AI/idea-slicer";
const MARKER = "generated by idea-slicer";

const sh = (cmd) => execSync(cmd, { encoding: "utf8" }).trim();
const esc = (s) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const slugify = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "idea";

const issues = JSON.parse(
  sh(`gh issue list --repo ${REPO} --state all --limit 500 --json number,title,body,state,labels`)
);
const has = (i, l) => i.labels.some((x) => x.name === l);
const ideas = issues.filter((i) => has(i, "idea"));
const thoughts = issues.filter((i) => has(i, "thought"));
for (const i of issues) i.body = (i.body || "").replace(/\r\n/g, "\n");

// ── 1. park hand-added thought issues into their parent idea's Unsorted lane ──
for (const t of thoughts) {
  const m = t.body.match(/Adds to #(\d+)/);
  if (!m) continue;
  const parent = ideas.find((i) => i.number === Number(m[1]));
  if (!parent) continue;
  const ref = `[#${t.number}]`;
  if (parent.body.includes(ref)) continue; // already merged (agent or earlier run)
  const gist = (
    t.body.split("\n").map((l) => l.trim()).find((l) => l && !l.startsWith("Adds to")) || t.title
  ).slice(0, 160);
  const line = `- ${gist} ${ref} — arrived via GitHub, not yet sliced — run /idea-slicer to place it`;
  parent.body = /## Unsorted\n/.test(parent.body)
    ? parent.body.replace(/## Unsorted\n/, `## Unsorted\n${line}\n`)
    : `${parent.body.trimEnd()}\n\n## Unsorted\n${line}\n`;
  fs.writeFileSync(".body.tmp.md", parent.body);
  sh(`gh issue edit ${parent.number} --repo ${REPO} --body-file .body.tmp.md`);
  fs.unlinkSync(".body.tmp.md");
  console.log(`parked thought #${t.number} into idea #${parent.number}`);
}

// ── 2. parse an idea body (maps/<slug>.md format) ──
const meta2 = (text, re) => { const m = text.match(re); return m ? m[1].trim() : ""; };
const list = (s) => (s ? s.split(",").map((x) => x.trim()).filter(Boolean) : []);

function parse(issue) {
  const body = issue.body;
  const section = (name) =>
    meta2(body, new RegExp(`## ${name}\\s*\\n([\\s\\S]*?)(?=\\n## |$)`));
  const summary =
    body.split(/^## /m)[0].split("\n").map((l) => l.trim())
      .filter((l) => l && !l.startsWith("#") && !/^\w[\w ]*:/.test(l))[0] || "";
  const stop = /^(Owns|Needs from|Steps):|^\d+\./;
  const depts = section("Departments").split(/^### /m).slice(1).map((chunk) => ({
    name: chunk.split("\n")[0].trim(),
    why: (chunk.split("\n").slice(1).find((l) => l.trim() && !stop.test(l)) || "").trim(),
    owns: list(meta2(chunk, /^Owns:\s*(.+)$/m)).filter((s) => s.toLowerCase() !== "nothing"),
    needsFrom: list(meta2(chunk, /^Needs from:\s*(.+)$/m)).filter((s) => s.toLowerCase() !== "nothing"),
    steps: [...chunk.matchAll(/^\d+\.\s+(.+)$/gm)].map((x) => x[1].trim()),
  }));
  return {
    title: meta2(body, /^# (.+)$/m) || issue.title,
    status: meta2(body, /^Status:\s*(\w+)/m) || (issue.state === "CLOSED" ? "done" : "open"),
    updated: meta2(body, /^Updated:\s*([0-9-]+)/m) || new Date().toISOString().slice(0, 10),
    emoji: meta2(body, /^Emoji:\s*(\S+)/m) || "🧠",
    summary,
    needs: [...section("This idea needs").matchAll(/^\d+\.\s+(.+)$/gm)].map((x) => x[1].trim()),
    depts,
    unsorted: [...section("Unsorted").matchAll(/^- (.+)$/gm)].map((x) => x[1].trim()),
    mermaid: meta2(body, /```mermaid\n([\s\S]*?)```/),
  };
}

// ── 3. render one page from template.html ──
function renderHtml(p, issue) {
  const tpl = fs.readFileSync("template.html", "utf8");
  const needs = p.needs
    .map((n, i) => `<span class="pill"><b>${i + 1}</b>${esc(n)}</span>`)
    .join(`<span class="arr">→</span>`);
  const cards = p.depts
    .map((d) => `
<div class="dept">
  <h3>${esc(d.name)}</h3>
  ${d.why ? `<div class="why">${esc(d.why)}</div>` : ""}
  <div class="lbl">Owns</div>
  <div class="chips">${d.owns.length ? d.owns.map((o) => `<span class="chip">${esc(o)}</span>`).join("") : '<span class="chip none">—</span>'}</div>
  <div class="lbl">Steps</div>
  <ol class="steps">${d.steps.map((s) => `<li>${esc(s)}</li>`).join("")}</ol>
  <div class="lbl">Needs from</div>
  <div class="chips">${d.needsFrom.length ? d.needsFrom.map((x) => `<span class="chip dep">${esc(x)}</span>`).join("") : '<span class="chip none">nothing — starts day one</span>'}</div>
</div>`)
    .join("\n");
  const unsortedHtml = p.unsorted.length
    ? p.unsorted.map((u) => {
        const [what, ...rest] = u.split(/\s+—\s+/);
        return `<div class="item"><span>${esc(what)}</span>${rest.length ? `<span class="why">${esc(rest.join(" — "))}</span>` : ""}</div>`;
      }).join("\n")
    : `<div class="item"><span>Nothing parked — every thought has a home.</span></div>`;
  return tpl
    .replaceAll("{{TITLE}}", esc(p.title))
    .replaceAll("{{SUB}}", esc(p.summary))
    .replaceAll("{{UPDATED}}", esc(p.updated))
    .replaceAll("{{STATUS}}", `${p.status} · issue #${issue.number}`)
    .replace("{{NEEDS}}", needs || '<span class="pill">Not sliced yet — run /idea-slicer</span>')
    .replace("{{CARDS}}", cards || "<p>No departments yet.</p>")
    .replace("{{MERMAID}}", p.mermaid || "flowchart TD\n  A[No diagram yet]")
    .replace("{{UNSORTED}}", unsortedHtml);
}

// ── 4. rebuild pages + manifest ──
for (const f of fs.readdirSync(".")) {
  if (f.endsWith(".html") && f !== "index.html" && fs.readFileSync(f, "utf8").includes(MARKER))
    fs.unlinkSync(f); // stale generated page (renamed/deleted idea)
}
fs.mkdirSync("maps", { recursive: true });
const manifest = [];
const seen = new Set();
for (const issue of ideas) {
  let slug = slugify(issue.title);
  while (seen.has(slug)) slug += "-2";
  seen.add(slug);
  const p = parse(issue);
  fs.writeFileSync(`${slug}.html`, renderHtml(p, issue));
  fs.writeFileSync(`maps/${slug}.md`, issue.body.trim() + "\n");
  manifest.push({
    file: `${slug}.html`,
    title: p.title,
    desc: p.summary.slice(0, 200),
    date: p.updated,
    emoji: p.emoji,
    status: p.status === "done" ? "done" : "open",
    issue: `#${issue.number}`,
  });
}
manifest.sort((a, b) => String(b.date).localeCompare(String(a.date)));
fs.writeFileSync("pages.json", JSON.stringify(manifest, null, 2) + "\n");
console.log(`rendered ${ideas.length} idea(s)`);
