#!/usr/bin/env node
// Regenerates idea map pages + pages.json from GitHub issues.
// Runs in GitHub Actions on issue events. No dependencies.
const { execSync } = require("child_process");
const fs = require("fs");

const REPO = "TR3-AI/idea-slicer";
const MARKER = "generated by idea-slicer";

const sh = (cmd) => execSync(cmd, { encoding: "utf8" }).trim();
const esc = (s) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const slugify = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "idea";

const issues = JSON.parse(
  sh(`gh issue list --repo ${REPO} --state all --limit 500 --json number,title,body,state,labels`)
);
const has = (i, l) => i.labels.some((x) => x.name === l);
const ideas = issues.filter((i) => has(i, "idea"));
const thoughts = issues.filter((i) => has(i, "thought"));
for (const i of issues) i.body = (i.body || "").replace(/\r\n/g, "\n");

// ── 1. park hand-added thought issues into their parent idea's Unsorted lane ──
for (const t of thoughts) {
  const m = t.body.match(/Adds to #(\d+)/);
  if (!m) continue;
  const parent = ideas.find((i) => i.number === Number(m[1]));
  if (!parent) continue;
  // nest the thought under its idea (GitHub sub-issues; idempotent)
  const subs = JSON.parse(sh(`gh api repos/${REPO}/issues/${parent.number}/sub_issues --jq "[.[].number]"`));
  if (!subs.includes(t.number)) {
    const subId = sh(`gh api repos/${REPO}/issues/${t.number} --jq .id`);
    sh(`gh api repos/${REPO}/issues/${parent.number}/sub_issues -X POST -F sub_issue_id=${subId}`);
    console.log(`nested thought #${t.number} under idea #${parent.number}`);
  }
  const ref = `[#${t.number}]`;
  if (parent.body.includes(ref)) continue; // already merged (agent or earlier run)
  const gist = (
    t.body.split("\n").map((l) => l.trim()).find((l) => l && !l.startsWith("Adds to")) || t.title
  ).slice(0, 160);
  const line = `- ${gist} ${ref} — arrived via GitHub, not yet sliced — run /ideaslicer to place it`;
  parent.body = /## Unsorted\n/.test(parent.body)
    ? parent.body.replace(/## Unsorted\n/, `## Unsorted\n${line}\n`)
    : `${parent.body.trimEnd()}\n\n## Unsorted\n${line}\n`;
  fs.writeFileSync(".body.tmp.md", parent.body);
  sh(`gh issue edit ${parent.number} --repo ${REPO} --body-file .body.tmp.md`);
  fs.unlinkSync(".body.tmp.md");
  console.log(`parked thought #${t.number} into idea #${parent.number}`);
}

// ── 2. parse an idea body (maps/<slug>.md format) ──
const meta2 = (text, re) => { const m = text.match(re); return m ? m[1].trim() : ""; };
const list = (s) => (s ? s.split(",").map((x) => x.trim()).filter(Boolean) : []);

function parse(issue) {
  const body = issue.body;
  const section = (name) =>
    meta2(body, new RegExp(`## ${name}\\s*\\n([\\s\\S]*?)(?=\\n## |$)`));
  const summary =
    body.split(/^## /m)[0].split("\n").map((l) => l.trim())
      .filter((l) => l && !l.startsWith("#") && !/^\w[\w ]*:/.test(l))[0] || "";
  const stop = /^(Owns|Needs from|Steps|Readiness|Icon|Responsibility|Starts when|Completes when|Boundary|Inputs|Outputs):|^\d+\./;
  const RMAP = { now: "ready", "after-contract": "contract", waiting: "waiting-internal", blocked: "waiting-external" };
  const STATES = ["ready", "ready-mocks", "contract", "waiting-internal", "waiting-external", "waiting-owner", "joint-design"];
  const depts = section("Departments").split(/^### /m).slice(1).map((chunk) => {
    const raw = meta2(chunk, /^Readiness:\s*([a-z-]+)/m);
    const r = RMAP[raw] || raw;
    return {
      name: chunk.split("\n")[0].trim(),
      readiness: STATES.includes(r) ? r : "ready",
      icon: meta2(chunk, /^Icon:\s*(\S+)/m) || "📦",
      responsibility: meta2(chunk, /^Responsibility:\s*(.+)$/m),
      why: (chunk.split("\n").slice(1).find((l) => l.trim() && !stop.test(l)) || "").trim(),
      starts: meta2(chunk, /^Starts when:\s*(.+)$/m),
      completes: meta2(chunk, /^Completes when:\s*(.+)$/m),
      boundary: meta2(chunk, /^Boundary:\s*(.+)$/m),
      owns: list(meta2(chunk, /^Owns:\s*(.+)$/m)).filter((s) => s.toLowerCase() !== "nothing"),
      inputs: meta2(chunk, /^Inputs:\s*(.+)$/m),
      outputs: meta2(chunk, /^Outputs:\s*(.+)$/m),
      needsFrom: list(meta2(chunk, /^Needs from:\s*(.+)$/m)).filter((s) => s.toLowerCase() !== "nothing"),
      steps: [...chunk.matchAll(/^\d+\.\s+(.+)$/gm)].map((x) => x[1].trim()),
      structure: [],
    };
  });
  const tree = section("Structure tree").replace(/^```[a-z]*\n?/i, "").replace(/```\s*$/, "").trim();
  const treeRoot = parseTree(tree);
  for (const d of depts) {
    const tn = treeRoot.children.find((c) => c.name.toLowerCase() === d.name.toLowerCase());
    if (tn) d.structure = tn.children;
  }
  const report = section("Consolidation report").split("\n").map((l) => l.trim()).filter(Boolean).join(" · ");
  const kv = (line) => {
    const out = {};
    for (const part of line.split("|").map((s) => s.trim())) {
      const ci = part.indexOf(":");
      if (ci > 0) out[part.slice(0, ci).trim().toLowerCase()] = part.slice(ci + 1).trim();
    }
    return out;
  };
  const groups = [...section("Correlated parallel groups").matchAll(/^- (.+)$/gm)].map((x) => {
    const o = kv(x[1]);
    return { name: o.group || "", members: o.members || "", snap: (o.snap || "").replace(/[^0-9]/g, ""), mode: o.mode || "", contract: o.contract || "", risk: o.risk || "" };
  });
  const deps = [...section("Dependency matrix").matchAll(/^- (.+)$/gm)].map((x) => {
    const o = kv(x[1]);
    const [prod, cons] = (x[1].split("|")[0] || "").split("→").map((s) => s.trim());
    return { prod: prod || "", cons: cons || "", supplies: o.supplies || "", type: o.type || "", blocking: o.blocking || "", mockable: o.mockable || "" };
  });
  const snaps = [...section("Snap ranking").matchAll(/^\d+\.\s+(.+)$/gm)].map((x) => {
    const seg = x[1].split(" — ").map((s) => s.trim());
    return { conn: seg[0] || "", score: (seg[1] || "").replace(/[^0-9]/g, ""), why: seg[2] || "", work: seg.slice(3).join(" — ") };
  });
  const mermaidIn = (sec) => meta2(section(sec), /```mermaid\n([\s\S]*?)```/);
  return {
    title: meta2(body, /^# (.+)$/m) || issue.title,
    status: meta2(body, /^Status:\s*(\w+)/m) || (issue.state === "CLOSED" ? "done" : "open"),
    updated: meta2(body, /^Updated:\s*([0-9-]+)/m) || new Date().toISOString().slice(0, 10),
    emoji: meta2(body, /^Emoji:\s*(\S+)/m) || "🧠",
    system: meta2(body, /^System:\s*(\w+)/m),
    reco: meta2(body, /^Recommended:\s*(.+)$/m),
    summary,
    flow: mermaidIn("Operating flow"),
    needs: [...section("This idea needs").matchAll(/^\d+\.\s+(.+)$/gm)].map((x) => x[1].trim()),
    depts, groups, deps, snaps,
    report,
    unresolved: [...section("Unresolved").matchAll(/^- (.+)$/gm)].map((x) => x[1].trim()),
    unsorted: [...section("Unsorted").matchAll(/^- (.+)$/gm)].map((x) => x[1].trim()),
    mermaid: mermaidIn("Diagram") || meta2(body, /```mermaid\n([\s\S]*?)```/),
  };
}

// ── 2b. parse ASCII tree-art into nested nodes ──
function parseTree(text) {
  const lines = text.split("\n").filter((l) => l.trim());
  const root = { name: (lines[0] || "PROJECT").trim(), children: [] };
  const stack = [root];
  for (const raw of lines.slice(1)) {
    const bi = raw.search(/[├└]──/);
    if (bi === -1) continue;
    const depth = Math.floor(bi / 4) + 1;
    const label = raw.slice(bi).replace(/^[├└]──\s?/, "").trim();
    const m = label.match(/^(.*?)\s*\((module|section|feature)(?::\s*([a-z-]+))?\)\s*$/i);
    const node = {
      name: m ? m[1].trim() : label,
      type: m ? m[2].toLowerCase() : depth === 2 ? "section" : "feature",
      mtype: m && m[3] ? m[3] : null,
      children: [],
    };
    (stack[depth - 1] || root).children.push(node);
    stack[depth] = node;
    stack.length = depth + 1;
  }
  return root;
}

// ── 3. render one page from template.html ──
function renderHtml(p, issue) {
  const tpl = fs.readFileSync("template.html", "utf8");
  const needs = p.needs
    .map((n, i) => `<span class="pill"><b>${i + 1}</b>${esc(n)}</span>`)
    .join(`<span class="arr">→</span>`);
  const ICONS = { section: "📁", module: "🧩", feature: "🔹" };
  const structHtml = (nodes, lvl) => nodes.map((n) => {
    const cls = n.type === "module" ? "mod" : n.type === "section" ? "sec" : "feat";
    const kids = n.children.length ? structHtml(n.children, lvl + 1) : "";
    const mtype = n.type === "module" && n.mtype ? `<span class="mtype">${esc(n.mtype)}</span>` : "";
    return `<div class="sline ${cls} d${Math.min(lvl, 3)}"><span class="sic">${ICONS[n.type] || "🔹"}</span><span class="sname">${esc(n.name)}</span>${mtype}</div>${kids}`;
  }).join("");
  const STATE_LABEL = { ready: "✅ ready", "ready-mocks": "✅ ready with mocks", contract: "📝 contract required", "waiting-internal": "⏳ waiting on internal", "waiting-external": "🚧 waiting on external", "waiting-owner": "🚧 waiting on owner", "joint-design": "🤝 joint design" };
  const kvline = (label, val, cls) => val ? `<div class="kv${cls ? " " + cls : ""}"><b>${label}</b> ${esc(val)}</div>` : "";
  const cardHtml = (d) => `
<div class="dept">
  <h3><span class="dicon">${esc(d.icon)}</span>${esc(d.name)}</h3>
  <div class="chips"><span class="chip state">${STATE_LABEL[d.readiness] || esc(d.readiness)}</span></div>
  ${(d.responsibility || d.why) ? `<div class="why">${esc(d.responsibility || d.why)}</div>` : ""}
  ${kvline("Starts when:", d.starts)}
  ${kvline("Completes when:", d.completes)}
  ${kvline("Boundary:", d.boundary, "boundary")}
  <div class="lbl">Owns</div>
  <div class="chips">${d.owns.length ? d.owns.map((o) => `<span class="chip">${esc(o)}</span>`).join("") : '<span class="chip none">—</span>'}</div>
  ${d.structure.length ? `<div class="lbl">Structure</div><div class="sblock">${structHtml(d.structure, 1)}</div>` : ""}
  <div class="lbl">Steps</div>
  <ol class="steps">${d.steps.map((s) => `<li>${esc(s)}</li>`).join("")}</ol>
  ${kvline("Inputs:", d.inputs)}
  ${kvline("Outputs:", d.outputs)}
  <div class="lbl">Needs from</div>
  <div class="chips">${d.needsFrom.length ? d.needsFrom.map((x) => `<span class="chip dep">${esc(x)}</span>`).join("") : '<span class="chip none">nothing — starts day one</span>'}</div>
</div>`;
  const BUCKETS = [
    ["now", "▶️ Can start in parallel now", ["ready", "ready-mocks"]],
    ["after-contract", "📝 Can start in parallel after contract definition", ["contract"]],
    ["joint-design", "🤝 Must perform joint design first", ["joint-design"]],
    ["waiting", "⏳ Must wait for another department", ["waiting-internal"]],
    ["blocked", "🚧 Blocked by external or owner dependency", ["waiting-external", "waiting-owner"]],
  ];
  const groups = BUCKETS.map(([key, label, states]) => {
    const ds = p.depts.filter((d) => states.includes(d.readiness));
    if (!ds.length) return "";
    return `<div class="bucket"><div class="bucket-head b-${key}">${label}</div><div class="grid">${ds.map(cardHtml).join("\n")}</div></div>`;
  }).filter(Boolean).join("\n");
  const snapBadge = (s) => {
    const n = Math.max(1, Math.min(5, parseInt(s, 10) || 3));
    return `<span class="snap s${n}">${n}</span>`;
  };
  const pgroups = p.groups.length ? p.groups.map((g) => `
<div class="group">
  <h4>${esc(g.name)} ${snapBadge(g.snap)}</h4>
  <div class="members">👥 ${esc(g.members)}${g.mode ? ` · <b>${esc(g.mode)}</b>` : ""}</div>
  ${kvline("Contract:", g.contract)}
  ${kvline("Main risk:", g.risk)}
</div>`).join("\n") : `<div class="group"><div class="members">No correlated groups identified yet.</div></div>`;
  const depRows = p.deps.map((d) => `<tr><td class="who">${esc(d.prod)}</td><td class="who">${esc(d.cons)}</td><td>${esc(d.supplies)}</td><td><span class="ttag t-${esc(d.type)}">${esc(d.type)}</span></td><td class="${d.blocking === "yes" ? "yes" : "no"}">${esc(d.blocking)}</td><td class="${d.mockable === "yes" ? "no" : ""}">${esc(d.mockable)}</td></tr>`).join("\n");
  const depsHtml = p.deps.length
    ? `<table class="deps"><tr><th>Producer</th><th>Consumer</th><th>Supplies</th><th>Type</th><th>Blocking</th><th>Mockable</th></tr>${depRows}</table>`
    : "<p>No dependencies mapped yet.</p>";
  const SLABEL = { 5: "Direct snap", 4: "Strong fit", 3: "Moderate fit", 2: "Weak fit", 1: "High-risk" };
  const snapsHtml = p.snaps.length ? p.snaps.map((s, i) => {
    const n = Math.max(1, Math.min(5, parseInt(s.score, 10) || 3));
    const meter = "●".repeat(n) + "○".repeat(5 - n);
    return `
<div class="snaprow">
  <div class="snapscore">${snapBadge(s.score)}<span class="meter m${n}">${meter}</span><span class="slabel">${SLABEL[n]}</span></div>
  <div class="smain"><span class="conn">${i + 1}. ${esc(s.conn)}</span><span class="swhy">${esc(s.why)}</span></div>
  ${s.work ? `<div class="swork"><b>needs</b>${esc(s.work)}</div>` : `<div class="swork none">snaps on contact</div>`}
</div>`;
  }).join("\n")
    : `<div class="snaprow"><span class="detail">No connections ranked yet.</span></div>`;
  const allMods = [];
  const walkMods = (nodes, dept) => nodes.forEach((n) => {
    if (n.type === "module") allMods.push({ name: n.name, dept, mtype: n.mtype });
    walkMods(n.children, dept);
  });
  p.depts.forEach((d) => walkMods(d.structure, d.name));
  const modulesHtml = allMods.length
    ? allMods.map((m) => `<span class="pill">🧩 <span class="mname">${esc(m.name)}</span> <span class="mdept">${esc(m.dept)}${m.mtype ? " · " + esc(m.mtype) : ""}</span></span>`).join("")
    : '<span class="pill">No genuine modules identified yet</span>';
  const nodeKind = (name) =>
    name.toLowerCase() === "bobby" ? "owner"
    : p.depts.some((d) => d.name.toLowerCase() === name.toLowerCase()) ? "dept" : "external";
  const gNodes = new Map();
  const gLinks = [];
  const addNode = (name) => { if (name && !gNodes.has(name)) gNodes.set(name, { id: name, kind: nodeKind(name) }); };
  for (const d of p.deps) {
    const prods = d.prod.toLowerCase() === "all departments" ? p.depts.map((x) => x.name) : [d.prod];
    for (const pr of prods) {
      addNode(pr); addNode(d.cons);
      gLinks.push({ source: pr, target: d.cons, type: d.type, blocking: d.blocking, mockable: d.mockable });
    }
  }
  p.depts.forEach((d) => addNode(d.name));
  const graphJson = JSON.stringify({ nodes: [...gNodes.values()], links: gLinks }).replace(/</g, "\\u003c");
  const itemHtml = (u) => {
    const [what, ...rest] = u.split(/\s+—\s+/);
    return `<div class="item"><span>${esc(what)}</span>${rest.length ? `<span class="why">${esc(rest.join(" — "))}</span>` : ""}</div>`;
  };
  const unresolvedHtml = p.unresolved.length
    ? p.unresolved.map(itemHtml).join("\n")
    : `<div class="item"><span>None flagged — nothing material is undecided.</span></div>`;
  const unsortedHtml = p.unsorted.length
    ? p.unsorted.map(itemHtml).join("\n")
    : `<div class="item"><span>Nothing parked — every thought has a home.</span></div>`;
  return tpl
    .replaceAll("{{TITLE}}", esc(p.title))
    .replaceAll("{{SUB}}", esc(p.summary))
    .replaceAll("{{RECO}}", esc(p.reco))
    .replaceAll("{{UPDATED}}", esc(p.updated))
    .replaceAll("{{STATUS}}", `${p.status} · issue #${issue.number}${p.system ? " · " + p.system : ""}`)
    .replace("{{NEEDS}}", needs || '<span class="pill">Not sliced yet — run /ideaslicer</span>')
    .replace("{{FLOW}}", p.flow || "flowchart TD\n  A[No operating flow yet]")
    .replace("{{DEPT_GROUPS}}", groups || "<p>No departments yet.</p>")
    .replace("{{REPORT}}", esc(p.report) || "")
    .replace("{{MODULES}}", modulesHtml)
    .replace("{{MERMAID}}", p.mermaid || "flowchart TD\n  A[No diagram yet]")
    .replace("{{GROUPS}}", pgroups)
    .replace("{{DEPS}}", depsHtml)
    .replace("{{GRAPH_JSON}}", graphJson)
    .replace("{{SNAPS}}", snapsHtml)
    .replace("{{UNRESOLVED}}", unresolvedHtml)
    .replace("{{UNSORTED}}", unsortedHtml);
}

// ── 4. rebuild pages + manifest ──
for (const f of fs.readdirSync(".")) {
  if (f.endsWith(".html") && f !== "index.html" && f !== "template.html" && fs.readFileSync(f, "utf8").includes(MARKER))
    fs.unlinkSync(f); // stale generated page (renamed/deleted idea)
}
fs.mkdirSync("maps", { recursive: true });
const manifest = [];
const seen = new Set();
for (const issue of ideas) {
  let slug = slugify(issue.title);
  while (seen.has(slug)) slug += "-2";
  seen.add(slug);
  const p = parse(issue);
  fs.writeFileSync(`${slug}.html`, renderHtml(p, issue));
  fs.writeFileSync(`maps/${slug}.md`, issue.body.trim() + "\n");
  manifest.push({
    file: `${slug}.html`,
    title: p.title,
    desc: p.summary.slice(0, 200),
    date: p.updated,
    emoji: p.emoji,
    status: p.status === "done" ? "done" : "open",
    issue: `#${issue.number}`,
  });
  // backstop: the visual link always lands on the issue, even if the model forgot to say it
  const url = `https://tr3-ai.github.io/idea-slicer/${slug}.html`;
  const comments = JSON.parse(sh(`gh api repos/${REPO}/issues/${issue.number}/comments --jq "[.[].body]"`));
  if (!comments.some((c) => (c || "").includes(url))) {
    fs.writeFileSync(".comment.tmp.md",
      `🗺️ **Visual map:** ${url}\n\nGoes live about a minute after each change and updates itself on every new thought.`);
    sh(`gh issue comment ${issue.number} --repo ${REPO} --body-file .comment.tmp.md`);
    fs.unlinkSync(".comment.tmp.md");
    console.log(`posted map link on issue #${issue.number}`);
  }
}
if (fs.existsSync("rulebook.html")) {
  manifest.push({
    file: "rulebook.html",
    title: "Skill rulebook",
    desc: "How idea-slicer works — the rules, the verified facts, and the FAQs.",
    date: new Date().toISOString().slice(0, 10),
    emoji: "📖",
    status: "done",
    issue: "",
  });
}
manifest.sort((a, b) => String(b.date).localeCompare(String(a.date)));
fs.writeFileSync("pages.json", JSON.stringify(manifest, null, 2) + "\n");
console.log(`rendered ${ideas.length} idea(s)`);
