#!/usr/bin/env node
// Regenerates idea map pages + pages.json from GitHub issues.
// Runs in GitHub Actions on issue events. No dependencies.
const { execSync } = require("child_process");
const fs = require("fs");

const REPO = "TR3-AI/idea-slicer";
const MARKER = "generated by idea-slicer";

const sh = (cmd) => execSync(cmd, { encoding: "utf8" }).trim();
const esc = (s) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const slugify = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "idea";

const issues = JSON.parse(
  sh(`gh issue list --repo ${REPO} --state all --limit 500 --json number,title,body,state,labels`)
);
const has = (i, l) => i.labels.some((x) => x.name === l);
const ideas = issues.filter((i) => has(i, "idea"));
const thoughts = issues.filter((i) => has(i, "thought"));
for (const i of issues) i.body = (i.body || "").replace(/\r\n/g, "\n");

// ── 1. park hand-added thought issues into their parent idea's Unsorted lane ──
for (const t of thoughts) {
  const m = t.body.match(/Adds to #(\d+)/);
  if (!m) continue;
  const parent = ideas.find((i) => i.number === Number(m[1]));
  if (!parent) continue;
  // nest the thought under its idea (GitHub sub-issues; idempotent)
  const subs = JSON.parse(sh(`gh api repos/${REPO}/issues/${parent.number}/sub_issues --jq "[.[].number]"`));
  if (!subs.includes(t.number)) {
    const subId = sh(`gh api repos/${REPO}/issues/${t.number} --jq .id`);
    sh(`gh api repos/${REPO}/issues/${parent.number}/sub_issues -X POST -F sub_issue_id=${subId}`);
    console.log(`nested thought #${t.number} under idea #${parent.number}`);
  }
  const ref = `[#${t.number}]`;
  if (parent.body.includes(ref)) continue; // already merged (agent or earlier run)
  const gist = (
    t.body.split("\n").map((l) => l.trim()).find((l) => l && !l.startsWith("Adds to")) || t.title
  ).slice(0, 160);
  const line = `- ${gist} ${ref} — arrived via GitHub, not yet sliced — run /idea-slicer to place it`;
  parent.body = /## Unsorted\n/.test(parent.body)
    ? parent.body.replace(/## Unsorted\n/, `## Unsorted\n${line}\n`)
    : `${parent.body.trimEnd()}\n\n## Unsorted\n${line}\n`;
  fs.writeFileSync(".body.tmp.md", parent.body);
  sh(`gh issue edit ${parent.number} --repo ${REPO} --body-file .body.tmp.md`);
  fs.unlinkSync(".body.tmp.md");
  console.log(`parked thought #${t.number} into idea #${parent.number}`);
}

// ── 2. parse an idea body (maps/<slug>.md format) ──
const meta2 = (text, re) => { const m = text.match(re); return m ? m[1].trim() : ""; };
const list = (s) => (s ? s.split(",").map((x) => x.trim()).filter(Boolean) : []);

function parse(issue) {
  const body = issue.body;
  const section = (name) =>
    meta2(body, new RegExp(`## ${name}\\s*\\n([\\s\\S]*?)(?=\\n## |$)`));
  const summary =
    body.split(/^## /m)[0].split("\n").map((l) => l.trim())
      .filter((l) => l && !l.startsWith("#") && !/^\w[\w ]*:/.test(l))[0] || "";
  const stop = /^(Owns|Needs from|Steps|Readiness|Icon):|^\d+\./;
  const KEYS = ["now", "after-contract", "joint-design", "waiting", "blocked"];
  const depts = section("Departments").split(/^### /m).slice(1).map((chunk) => {
    const r = meta2(chunk, /^Readiness:\s*([a-z-]+)/m);
    return {
      name: chunk.split("\n")[0].trim(),
      readiness: KEYS.includes(r) ? r : "now",
      icon: meta2(chunk, /^Icon:\s*(\S+)/m) || "📦",
      why: (chunk.split("\n").slice(1).find((l) => l.trim() && !stop.test(l)) || "").trim(),
      owns: list(meta2(chunk, /^Owns:\s*(.+)$/m)).filter((s) => s.toLowerCase() !== "nothing"),
      needsFrom: list(meta2(chunk, /^Needs from:\s*(.+)$/m)).filter((s) => s.toLowerCase() !== "nothing"),
      steps: [...chunk.matchAll(/^\d+\.\s+(.+)$/gm)].map((x) => x[1].trim()),
      structure: [],
    };
  });
  const tree = section("Structure tree").replace(/^```[a-z]*\n?/i, "").replace(/```\s*$/, "").trim();
  const treeRoot = parseTree(tree);
  for (const d of depts) {
    const tn = treeRoot.children.find((c) => c.name.toLowerCase() === d.name.toLowerCase());
    if (tn) d.structure = tn.children;
  }
  const report = section("Consolidation report").split("\n").map((l) => l.trim()).filter(Boolean).join(" · ");
  return {
    title: meta2(body, /^# (.+)$/m) || issue.title,
    status: meta2(body, /^Status:\s*(\w+)/m) || (issue.state === "CLOSED" ? "done" : "open"),
    updated: meta2(body, /^Updated:\s*([0-9-]+)/m) || new Date().toISOString().slice(0, 10),
    emoji: meta2(body, /^Emoji:\s*(\S+)/m) || "🧠",
    summary,
    needs: [...section("This idea needs").matchAll(/^\d+\.\s+(.+)$/gm)].map((x) => x[1].trim()),
    depts,
    report,
    unresolved: [...section("Unresolved").matchAll(/^- (.+)$/gm)].map((x) => x[1].trim()),
    unsorted: [...section("Unsorted").matchAll(/^- (.+)$/gm)].map((x) => x[1].trim()),
    mermaid: meta2(body, /```mermaid\n([\s\S]*?)```/),
  };
}

// ── 2b. parse ASCII tree-art into nested nodes ──
function parseTree(text) {
  const lines = text.split("\n").filter((l) => l.trim());
  const root = { name: (lines[0] || "PROJECT").trim(), children: [] };
  const stack = [root];
  for (const raw of lines.slice(1)) {
    const bi = raw.search(/[├└]──/);
    if (bi === -1) continue;
    const depth = Math.floor(bi / 4) + 1;
    const label = raw.slice(bi).replace(/^[├└]──\s?/, "").trim();
    const m = label.match(/^(.*?)\s*\((module|section|feature)\)\s*$/i);
    const node = {
      name: m ? m[1].trim() : label,
      type: m ? m[2].toLowerCase() : depth === 2 ? "section" : "feature",
      children: [],
    };
    (stack[depth - 1] || root).children.push(node);
    stack[depth] = node;
    stack.length = depth + 1;
  }
  return root;
}

// ── 3. render one page from template.html ──
function renderHtml(p, issue) {
  const tpl = fs.readFileSync("template.html", "utf8");
  const needs = p.needs
    .map((n, i) => `<span class="pill"><b>${i + 1}</b>${esc(n)}</span>`)
    .join(`<span class="arr">→</span>`);
  const ICONS = { section: "📁", module: "🧩", feature: "🔹" };
  const structHtml = (nodes, lvl) => nodes.map((n) => {
    const cls = n.type === "module" ? "mod" : n.type === "section" ? "sec" : "feat";
    const kids = n.children.length ? structHtml(n.children, lvl + 1) : "";
    return `<div class="sline ${cls} d${Math.min(lvl, 3)}"><span class="sic">${ICONS[n.type] || "🔹"}</span><span class="sname">${esc(n.name)}</span></div>${kids}`;
  }).join("");
  const cardHtml = (d) => `
<div class="dept">
  <h3><span class="dicon">${esc(d.icon)}</span>${esc(d.name)}</h3>
  ${d.why ? `<div class="why">${esc(d.why)}</div>` : ""}
  <div class="lbl">Owns</div>
  <div class="chips">${d.owns.length ? d.owns.map((o) => `<span class="chip">${esc(o)}</span>`).join("") : '<span class="chip none">—</span>'}</div>
  ${d.structure.length ? `<div class="lbl">Structure</div><div class="sblock">${structHtml(d.structure, 1)}</div>` : ""}
  <div class="lbl">Steps</div>
  <ol class="steps">${d.steps.map((s) => `<li>${esc(s)}</li>`).join("")}</ol>
  <div class="lbl">Needs from</div>
  <div class="chips">${d.needsFrom.length ? d.needsFrom.map((x) => `<span class="chip dep">${esc(x)}</span>`).join("") : '<span class="chip none">nothing — starts day one</span>'}</div>
</div>`;
  const BUCKETS = [
    ["now", "▶️ Can start in parallel now"],
    ["after-contract", "📝 Can start in parallel after contract definition"],
    ["joint-design", "🤝 Must perform joint design first"],
    ["waiting", "⏳ Must wait for another department"],
    ["blocked", "🚧 Blocked by external or owner dependency"],
  ];
  const groups = BUCKETS.map(([key, label]) => {
    const ds = p.depts.filter((d) => d.readiness === key);
    if (!ds.length) return "";
    return `<div class="bucket"><div class="bucket-head b-${key}">${label}</div><div class="grid">${ds.map(cardHtml).join("\n")}</div></div>`;
  }).filter(Boolean).join("\n");
  const itemHtml = (u) => {
    const [what, ...rest] = u.split(/\s+—\s+/);
    return `<div class="item"><span>${esc(what)}</span>${rest.length ? `<span class="why">${esc(rest.join(" — "))}</span>` : ""}</div>`;
  };
  const unresolvedHtml = p.unresolved.length
    ? p.unresolved.map(itemHtml).join("\n")
    : `<div class="item"><span>None flagged — nothing material is undecided.</span></div>`;
  const unsortedHtml = p.unsorted.length
    ? p.unsorted.map(itemHtml).join("\n")
    : `<div class="item"><span>Nothing parked — every thought has a home.</span></div>`;
  return tpl
    .replaceAll("{{TITLE}}", esc(p.title))
    .replaceAll("{{SUB}}", esc(p.summary))
    .replaceAll("{{UPDATED}}", esc(p.updated))
    .replaceAll("{{STATUS}}", `${p.status} · issue #${issue.number}`)
    .replace("{{NEEDS}}", needs || '<span class="pill">Not sliced yet — run /idea-slicer</span>')
    .replace("{{DEPT_GROUPS}}", groups || "<p>No departments yet.</p>")
    .replace("{{REPORT}}", esc(p.report) || "")
    .replace("{{MERMAID}}", p.mermaid || "flowchart TD\n  A[No diagram yet]")
    .replace("{{UNRESOLVED}}", unresolvedHtml)
    .replace("{{UNSORTED}}", unsortedHtml);
}

// ── 4. rebuild pages + manifest ──
for (const f of fs.readdirSync(".")) {
  if (f.endsWith(".html") && f !== "index.html" && f !== "template.html" && fs.readFileSync(f, "utf8").includes(MARKER))
    fs.unlinkSync(f); // stale generated page (renamed/deleted idea)
}
fs.mkdirSync("maps", { recursive: true });
const manifest = [];
const seen = new Set();
for (const issue of ideas) {
  let slug = slugify(issue.title);
  while (seen.has(slug)) slug += "-2";
  seen.add(slug);
  const p = parse(issue);
  fs.writeFileSync(`${slug}.html`, renderHtml(p, issue));
  fs.writeFileSync(`maps/${slug}.md`, issue.body.trim() + "\n");
  manifest.push({
    file: `${slug}.html`,
    title: p.title,
    desc: p.summary.slice(0, 200),
    date: p.updated,
    emoji: p.emoji,
    status: p.status === "done" ? "done" : "open",
    issue: `#${issue.number}`,
  });
}
manifest.sort((a, b) => String(b.date).localeCompare(String(a.date)));
fs.writeFileSync("pages.json", JSON.stringify(manifest, null, 2) + "\n");
console.log(`rendered ${ideas.length} idea(s)`);
